### ISSUE TITLE
Commands require cheats to be enabled

### ISSUE THREAD

**Issue by RemagOfficial** [cojalexandru/totally-harmonious-item-stages#10]
### Minecraft Version

1.19.2

### Forge Version

43.2.10

### T.H.I.S. Version

0.1.1

### Describe your issue

if i player doesnt have cheats enabled you cant use any of the commands and with no other way to give stages then the player cant get any stages with no error message

### Log File related to your crash

didnt crash

### Crash Report

didnt crash

### Other mods

the pack is UniversIO, i am the maintainer

### Tried reproducing with just T.H.I.S.?

Yes

### Performance Enchancers

Rubidium

**Comment by cojalexandru** [comment]
That's intended behaviour, the commands should only be used by OP users or the console.
That's why most commands have a <player> argument.

**Comment by RemagOfficial** [comment]
how are stages intended to be given by ftbquests then?

**Comment by cojalexandru** [comment]
For the time being you could use something like KubsJS that adds custom rewards https://wiki.latvian.dev/books/kubejs-legacy/page/ftb-quests-integration

That's how we did it on our modpack.

**Comment by RemagOfficial** [comment]
that's like a bandaid fix, relying on another mod for a feature that should be part of this mod is annoying and a bad idea

**Comment by RemagOfficial** [comment]
for example gamestages has native ftbquests support and support for commands, if we didn't rely on this for stages I'd work on switching mods

**Comment by cojalexandru** [comment]
> For the time being you could use something like KubsJS that adds custom rewards https://wiki.latvian.dev/books/kubejs-legacy/page/ftb-quests-integration
> 
> That's how we did it on our modpack.

It works without KubeJS too, my bad.
Just have to use the `@p` parameter and have the "Run as player" argument unchecked, at least this worked for me with ftb-quests-forge-1902.5.8-build.345 and thitemstages-1.19.2-0.2-rc1
![image](https://github.com/cojalexandru/totally-harmonious-item-stages/assets/93152438/82a794d5-02d3-49b9-9976-8f9acff5bedc)

**Comment by RemagOfficial** [comment]
I'll test that later, thought I tried that but maybe not
