### ISSUE TITLE
Items not appearing in creative menu

### ISSUE THREAD

**Issue by Svetrikk** [cojalexandru/totally-harmonious-item-stages#14]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### T.H.I.S. Version

0.2.1

### Describe your issue

When this mod is installed, searching in creative inventory does not find the item I am searching for even though i am in the age.

### Log File related to your crash

https://pastebin.com/bBk5iMHP

### Other mods

[Melody (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/melody)
[RightClickHarvest (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Konkrete [Forge/NeoForge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Better Days (by wendall911)](https://www.curseforge.com/minecraft/mc-mods/betterdays)
[Visuality: Reforged (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/visuality-reforged)
[Spice of Life: Valheim Edition (by Txni)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-valheim-edition)
[Totally Harmonious Item Stages (by alexandr_0031)](https://www.curseforge.com/minecraft/mc-mods/totally-harmonious-item-stages)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Hang Glider [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/hang-glider)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Lootr (Forge & NeoForge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Bartering Station [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Obscure Tooltips (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips)
[Stack Refill (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/stack-refill)
[Prism [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Equipment Compare [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
[Diagonal Walls (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-walls)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[FancyMenu (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu)
[Legendary Tooltips [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
[Item Highlighter [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[Toast Control (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/toast-control)
[Loot Beams: Relooted! (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/loot-beams)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[Diagonal Fences [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Diagonal Windows [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-windows)
[Simple Magnets (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Merchant Markers [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/merchant-markers)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Functional Storage (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/functional-storage)
[Overflowing Bars [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/overflowing-bars)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Item Borders [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-borders)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Clean Swing Through Grass (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/clean-swing-through-grass)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Fantasy's Furniture (by ApexModder)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[Loot Journal (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/loot-journal)
[Open Loader (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/open-loader)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Stellar View (by Povstalec)](https://www.curseforge.com/minecraft/mc-mods/stellarview)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)

### Tried reproducing with just T.H.I.S.?

Yes

### Performance Enchancers

None of the above

**Comment by cojalexandru** [comment]
Uhh, sorry for the late reponse wanted to respond earlier but just got lost in other things.
So I think what you're experiencing it's because the vanilla creative search bar searches for the item names specifically and if you have items staged with a custom name you won't be able to find them in there because all of the restricted items will have the same name.

**Comment by Svetrikk** [comment]
Even when I was in the stage it wouldn’t find those items. I tried to re-enable the mod and restart Minecraft and since then it works as usual.
