### ISSUE TITLE
Problem while loading in game after Patch 1.18.2-0.1.1

### ISSUE THREAD

**Issue by Steampunkgears** [cojalexandru/totally-harmonious-item-stages#4]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.85
Environment: Singleplayer / Multiplayer

Hey there.
 So I ran into an issue I have no clue what it is. But I have confirmed when I run the latest 1.18.2-0.1.1 I get the following msg on loading into my MP server. When I reverted back to 1.18.2-0.7 everything is fine.
[https://imgur.com/nivmG0d](url)

 Wanted to post this as a possible problem. I tired a number of things from completely deleting the old config folders before updating. Not sure what else to do here.

**Comment by SheReyy** [comment]
We'll look into it as soon as possible, but for now, the restriction file used and a log file related to this issue would be useful.

**Comment by Steampunkgears** [comment]
I have not done anything yet to those files and are the same as they are when downloaded fresh. Here is a copy of what is on our server currently. We would like to add more to it but obviously want to make sure this issue is taken care of first.
[https://drive.google.com/drive/folders/1oFjVpdWkfVDxxhB_huQaPT1LFbOUSXiL?usp=sharing](url)

**Comment by SheReyy** [comment]
Ok, so this should be fixed in the next update. Thx for reporting this.

**Comment by Steampunkgears** [comment]
How are you able to understand that photo? or was it something missing from the files sent?

**Comment by SheReyy** [comment]
⭐Magic⭐ Basically some command arguments were the ⭐problem⭐
