### ISSUE TITLE
Registry Object Not Present for EE (only when THIS is utilizing Item Stages)

### ISSUE THREAD

**Issue by itsTort** [cojalexandru/totally-harmonious-item-stages#5]
### Minecraft Version

1.19.2

### Forge Version

43.2.14

### T.H.I.S. Version

thitemstages-1.19.2-0.1.1

### Describe your issue

Here is a pastebin of the test restriction file: https://pastebin.com/ZW898tu1

After a few hours of messing with this, I finally decided to try only emendatusenigmatica and lifting the restrictions.  No matter what I do though, I am getting the error report in the Crash Report section.   Same report over and over, letting me know about the steel block. 

This issue only happens when any Item Stage is utilized. Without, the game loads fine (and the EE steel block exists). 

### Log File related to your crash

https://pastebin.com/VsWKaYZP

### Crash Report

https://pastebin.com/VsWKaYZP

### Other mods

EmendatusEnigmatica and THIS

### Tried reproducing with just T.H.I.S.?

No

### Performance Enchancers

None of the above

**Comment by cojalexandru** [comment]
Try removing lines 21 through 23:
```
      {
        "item": "emendatusenigmatica:steel_block"
      },
```
from the restriction file.

Honestly as far as I can tell there just isn't an item with that id.

**Comment by itsTort** [comment]
![image](https://github.com/cojalexandru/totally-harmonious-item-stages/assets/67648567/17e8f761-aa37-417b-beb5-16021d7aef72)

I am at a complete loss right now. The item totally exists, but that's besides the point.

The only reason I put that item on that line is because I tried to load up a restriction where EE/Steel Block was not on there, and I got that error.  I thought I needed to make an exception for it to allow it to register.

That being said, I fired everything up this morning, and I must have done something differently because now things are working the way they are expected to.

The only thing that's missing is the Integration w/ Improved Mobs, but thats just because it isn't present in 1.19 I think :(

**Comment by itsTort** [comment]
[age_1.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901172/age_1.txt)
[age_2.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901174/age_2.txt)
[age_3.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901175/age_3.txt)
[age_4.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901176/age_4.txt)
[age_5.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901177/age_5.txt)
[age_6.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901178/age_6.txt)
[age_7.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901179/age_7.txt)
[crash-2023-06-28_18.29.30-client.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901181/crash-2023-06-28_18.29.30-client.txt)
[crash-2023-06-28_18.26.35-client.txt](https://github.com/cojalexandru/totally-harmonious-item-stages/files/11901186/crash-2023-06-28_18.26.35-client.txt)

Welp, thats super frustrating. It seems that once you add to the item exceptions/item list, it's causing the Steel Block issue.

I attached all 7 of my ages here. Not a single file is calling to emendatusenigmatica, or a steel block of any type. 

Crash is consistent, I can't even load the client. 


Would definitely appreciate any help here.     Feeling extremely defeated right now, after putting all that work in to get hit in the face with something I thought was gone.. lol 

I seriously hope I just did something dumb somewhere, and this is an easy fix. 

Thanks for taking the time to look at this!

**EDIT 1**
So far, I've narrowed it down to only Age 3.    Age 1, 2, 4, 6, and 7 all load just fine.

**Comment by cojalexandru** [comment]
There appears to be a similar issue on the Emendatus Enigmatica GitHub page (https://github.com/Ridanisaurus/EmendatusEnigmatica/issues/202), the crash is very much the same just the item id is different.

Are you sure that T.H.I.S is causing the crash, have you tried running the game without it to see if you still get the crash?

**Comment by itsTort** [comment]
Interesting! Yeah, in this case it was totally THIS causing it, but it seems it was due to my own mistake. 

Age 3, for my exception list -- Line 73 was missing a comma.  

No idea why it was throwing an EE error, but I literally just got the world to load after narrowing it down to that after like 8 reloads and slowly adding things back to that file.. hah.

The EE error really threw me off and made this extra confusing.

**Comment by Ridanisaurus** [comment]
I will be implementing a fail safe in the upcoming release of EE to prevent it from showing up as the culprit for the crash by stopping data-gen if another mod failed at an earlier stage. 
As far as I understood is due to a mod failing before EE started its data-gen, and forge failed to get the modloading screen.
