### ISSUE TITLE
Items are still able to be used/mine blocks

### ISSUE THREAD

**Issue by liopyu** [cojalexandru/totally-harmonious-item-stages#7]
### Minecraft Version

1.19.2

### Forge Version

43.2.0

### T.H.I.S. Version

1.19.2-0.1.1

### Describe your issue

As the title says I'm unable to restrict items from being used upon right/left clicks. 
![2023-07-17_09 38 54](https://github.com/cojalexandru/totally-harmonious-item-stages/assets/130418550/3ca6ef27-af14-4604-b22b-4ba7d51ce63c)
![2023-07-17_09 38 57](https://github.com/cojalexandru/totally-harmonious-item-stages/assets/130418550/6ead96cc-4cf5-41c9-afdc-e65fc03a3bbc)

thitemstages-common.toml:
https://pastebin.com/50cRNARQ

restrictions file:
https://pastebin.com/RZucA9Ps

### Log File related to your crash

N/A

### Other mods

No other mods are being used in this example.

### Tried reproducing with just T.H.I.S.?

Yes

### Performance Enchancers

None of the above

**Comment by Teal0** [comment]
I am having the same issue. The only restriction that works is that I cannot hit mobs with the restricted tools. Apart from this I can break blocks or use the right click abilities of tools without restrictions.

**Comment by cojalexandru** [comment]
Yeah, my bad... Didn't use the proper events.
Will be fixed in the next update, probably at the end of the week.
