### ISSUE TITLE
Show the item name even if item is restricted

### ISSUE THREAD

**Issue by AleDev2105** [cojalexandru/totally-harmonious-item-stages#8]
### Minecraft Version

1.19.2

### Forge Version

43.2.21

### T.H.I.S. Version

0.1.1

### Describe your issue

When in the restriction life I created a new stage, I set "advancedTooltips" key to "ALWAYS" and the item name was not displayed, but when I set the same key to "ADVANCED" or "NONE" the tooltips were no longer shown but I could see the item name.

### Log File related to your crash

Is not a crash, only a bug (maybe).

### Other mods

Rei with Rei Plugin Compatibilities
KubeJS (without game modification)

### Tried reproducing with just T.H.I.S.?

Yes

### Performance Enchancers

None of the above

**Comment by cojalexandru** [comment]
What you're explaining seems to be the expected behavior.
From the [wiki](https://wiki.decursioteam.com/mods/totally-harmonious-item-stages/1.18-1.19.2/creating-restrictions/settings):
```
"advancedTooltips": <ALWAYS/NONE/ADVANCED>
-ALWAYS: the restricted items will always have tooltips explaining the way they're restricted
-NONE: the restricted items will never have tooltips explaining the way they're restricted
-ADVANCED: the restricted items will have tooltips explaining the way they're restricted only when the client has the advanced tooltips (F3+H) enabled
```
